spring.application.name=GymManager
# Conexion a mi MySQL

spring.datasource.url=CADENA_CONEXION
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_PASSWORD

# JPA/Hibernate
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false